// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package httptun

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	// Register registers the client as a proxy target. The clent MUST provide
	// an X-Scope-ProxyID header when calling this method that uniquely identifies
	// themselves amongst other connected peers. Once connected, the client
	// should respond to any request provided by the server.
	Register(ctx context.Context, opts ...grpc.CallOption) (Proxy_RegisterClient, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) Register(ctx context.Context, opts ...grpc.CallOption) (Proxy_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[0], "/httptun.Proxy/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyRegisterClient{stream}
	return x, nil
}

type Proxy_RegisterClient interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type proxyRegisterClient struct {
	grpc.ClientStream
}

func (x *proxyRegisterClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyRegisterClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	// Register registers the client as a proxy target. The clent MUST provide
	// an X-Scope-ProxyID header when calling this method that uniquely identifies
	// themselves amongst other connected peers. Once connected, the client
	// should respond to any request provided by the server.
	Register(Proxy_RegisterServer) error
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) Register(Proxy_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).Register(&proxyRegisterServer{stream})
}

type Proxy_RegisterServer interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type proxyRegisterServer struct {
	grpc.ServerStream
}

func (x *proxyRegisterServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyRegisterServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "httptun.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Proxy_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "httpproxy.proto",
}
